### ISSUE TITLE
KeyError: 'coord_AG'

### ISSUE THREAD

**Issue by Yuiceee** [WangZhiwei9/MIPE#1]
hello, i noticed that there is a error about data  and cvdata.pkl does't have key about 'coord'

> Traceback (most recent call last):
  File "/root/projects/MIPE/code/main.py", line 45, in <module>
    ag_edge_ind, ab_edge_ind = CreateGearnetGraph(train_data_PECAN[i])# Edge
  File "/root/projects/MIPE/code/utils.py", line 98, in CreateGearnetGraph
    dis_pq.append(dis_pairs(data["coord_AG"][p], data["coord_AG"][q]))
KeyError: 'coord_AG'

**Comment by WangZhiwei9** [comment]
Thank you for your attention to our work. We will update the dataset as soon as possible.
